# Generated by Django 2.2.1 on 2019-06-02 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_press'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Press')),
            ],
        ),
    ]
